apiVersion: v1
kind: Service
metadata:
  name: teste-site
  namespace: teste-site
spec:
  selector:
    app: teste-site
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 5000
  type: LoadBalancer
    
